### ISSUE TITLE
Add footer to login page with dynamic text

### ISSUE THREAD

**Issue by MarvinJWendt** [MarvinJWendt/traefik-guardian#11]
A footer should be added to the login page.

This can be used as reference:
![image](https://user-images.githubusercontent.com/31022056/193801274-a7a727d0-bb08-4de5-8cb6-1f826a74618a.png)

We don't need the social-media icons.

The logo should be a black and white version of our logo:

[Traefik Guardian Logo.zip](https://github.com/MarvinJWendt/traefik-guardian/files/9705275/Traefik.Guardian.Logo.zip)

The copyright text should be modifiable via an environment variable (injected via go template).

**Comment by Aragur** [comment]
I would like to add this feature

**Comment by MarvinJWendt** [comment]
Sure, I've assigned you to this one :)
