### ISSUE TITLE
example is missing a loadbalancer

### ISSUE THREAD

**Issue by scharc** [MarvinJWendt/traefik-guardian#20]
I tried the example code and had to adjust the labels for traefik to add a loadbalancer to port 80:

```    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.rule=Host(`auth.localhost`) || Path(`/traefik-guardian-session-share`) # Replace auth.test.localhost with your auth host defined above.
      - traefik.http.routers.auth.tls.certresolver=le
      - traefik.http.routers.auth.entrypoints=websecure
      - traefik.http.routers.auth.service=auth
      - traefik.http.middlewares.traefik-guardian.forwardauth.address=http://traefik-guardian/auth
      - traefik.http.services.auth.loadbalancer.server.port=80
 ´´

**Comment by MarvinJWendt** [comment]
Traefik Guardian only exposes one port, so no loadbalancer should be needed:

![image](https://user-images.githubusercontent.com/31022056/201471782-5abda7b1-7c82-48a7-b66a-ce6da3147018.png)
(https://doc.traefik.io/traefik/providers/docker/)

Are you using the latest Traefik version?

**Comment by scharc** [comment]
Sorry, my fault. 

I have set `exposedbydefault` to false and therefore need the loadbalancer. 

anyways would be nice to put it in there as comment for people looking for the port  instead of going into the go binary and find the server part.

**Comment by MarvinJWendt** [comment]
> anyways would be nice to put it in there as comment for people looking for the port instead of going into the go binary and find the server part.

Yes I will include it in the docs, thanks for pointing out. A litte hint: Docker images always have the port in the Dockerfile, you don't have to go to the code: https://github.com/MarvinJWendt/traefik-guardian/blob/912fc91c958d04631413cdf0891221556970e726/Dockerfile#L13
